name: Backpacks
version: 1.0.0
main: com.supafloof.backpacks.Backpacks
api-version: 1.19
author: SupaFloof Games, LLC
description: Portable storage containers with upgradeable capacity

commands:
  backpack:
    description: Main backpack command
    usage: /backpack <help|give|reload>
    aliases: [bp]
    permission: backpacks.use

permissions:
  backpacks.use:
    description: Allows using backpack commands
    default: true
  backpacks.give:
    description: Allows giving backpacks and doublers to players
    default: op
  backpacks.admin:
    description: Allows reloading configuration
    default: op