name: Backpacks
version: 1.0.0
main: com.supafloof.backpacks.Backpacks
api-version: '1.21'
author: SupaFloof Games, LLC
description: Portable storage containers with personal and item-based backpacks

commands:
  backpack:
    description: Backpack administration commands
    usage: /<command> [help|give|reload]
    aliases: [backpacks]
  bp:
    description: Open your personal backpack
    usage: /<command>

permissions:
  backpacks.use:
    description: Allows using /bp to open personal backpack
    default: false
  backpacks.give:
    description: Allows giving backpack items to players
    default: op
  backpacks.admin:
    description: Allows reloading plugin configuration
    default: op